# Shared Zuul v3 definitions for OpenStack CI.

# These jobs are used in api-site, openstack-manuals, and security-doc
# repositories.

- job:
    name: build-tox-manuals
    description: |
      Base job to build manual related documents. These build jobs
      invoke a tox command and expect the published content to be in
      publish-docs/html directory. This content is published on the root of
      the website.

      Note that this build job does not create a root-marker file,
      this has to be done by scripts called from tox.
    parent: opendev-tox-docs
    success-url: publish-docs/html/
    roles:
      - zuul: zuul/zuul-jobs
    vars:
      sphinx_build_dir: 'publish-docs'
      tox_environment:
        # The tox job writes the root-marker file directly and thus
        # needs the following variables set:
        ZUUL_PROJECT: '{{ zuul.project.name }}'
        ZUUL_BRANCH: '{{ zuul.branch }}'
        ZUUL_UUID: '{{ zuul.build }}'
        ZUUL_NEWREF: '{{ zuul.ref }}'

- job:
    name: build-tox-manuals-publishdocs
    parent: build-tox-manuals
    vars:
      tox_envlist: publishdocs

# Templates to easily group jobs.
- project-template:
    name: openstack-manuals-jobs
    description: |
      Runs jobs for non-translated documents.
    check:
      jobs:
        - openstack-tox-linters
        - build-tox-manuals-publishdocs
    gate:
      jobs:
        - openstack-tox-linters
        - build-tox-manuals-publishdocs
    promote:
      jobs:
        - promote-openstack-manuals

# Configuration for this repository, determines which jobs to run.
- project:
    templates:
      - openstack-manuals-jobs
